matrix:
    include:
        - dist: xenial
          language: python
          python: 3.7.3
          install:
            - pip install -r server/requirements.txt
          before_script:
            - cd server
          script:
            - python -m unittest discover
