dist: xenial
branches:
  only:
  - server
language: python
python: 3.7.3
install:
- pip install -r server/requirements.txt
before_script:
- cd server
script:
- python -m unittest discover
before_deploy:
- cd server
deploy:
  provider: heroku
  app: smart-shopping-list-pwr-api
  on:
    repo: zpi-2019/Smart-shopping-list
  api_key:
    secure: KWLZHk4uwBBawYoM4+4Wl+xf12cPxNRxBMNBS7GHv/IEeIpIc/GI3Vfjyhbym0xgoCkrv2uApipov7K8lCqt9KqJVh43bCzLMuaBhwKaHsjgz57RqBubK1Yj6TMTGf43Z8m7cc929h4iUFkUeZFx9nksCR9KqIMHwDmlhsOPrG4gCuXDerkEVc8DC0Nlt5dKved5CwjFRbaXmCrckBDEKAtL7wRRTjV+/UYpWCGz8QXpmYssYMj7PaSpo6UQnftXNdaIbsmWqDaUjFdsdFt9+D3ut/4p+UL2Y60mgXxZ1+OjZGg3fcJ2Y1xUa3Q2zpyRYURpql4sFZoh14gM46i+J+l/ftWhcFFMZ6hw7MpfYtvaIKvwtsc0f3nDfrIe6gxrWAxk66UewbYE/9NC8Ik+ZVMMSYTeNBYlsFXLAaOSUJ0vWPNhhAR87oTgYuDbJM69HxYQmdXvqSfmpRTKA2uT6Co0bmmbplzQuR90syG8NdYrKwgoxFe/JBvBxmtaVEY3KbwcG+KbPnCKS/r/xxu0JJrJFwZzYrFaT0QviyWiSyIBDAx/t/3bG9B4yaS9R4N1cwTXeIl9Z8W5odLgv4Z8KM16DL0aavHTxgVFujoE6tGDDD+jP2lyANYMiratrVvsohtv3pXRtbFs19kYdTU7MNVX0xqvU62RtxdEzdbbX5s=
