matrix:
    include:
        - dist: xenial
          language: python
          python: 3.7
          before_intall:
            - cd server
          install:
            - pip install -r requirements.txt
          before_script:
            - cd server
          script:
            - python -m unittests discover
